logging:
  level:
    root: info
    com.oyatrij.com.oyatrij.springoauthsociallogin: debug

server:
  port: 8080

spring:
  application:
    name: spring-oauth-social-login
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
datasource:
  url: jdbc:mysql://localhost:3306/oyatrijtest
  username: oytarijtest
  password: oytarijtest
security:
  oauth2:
    client:
      registration:
        google:
          client-id: #your client-id
          client-secret: #your client-secret
          scope: email
        naver:
          client-id:
          client-secret:
          redirect-uri:
          authorization-grant-type: authorization_code
          scope: email
          cleient-name: Naver
      provider:
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response