logging:
  level:
    root: info
    com.oyatrij.com.oyatrij.springoauthsociallogin: debug

server:
  port: 8080

spring:
  application:
    name: spring-oauth-social-login
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

datasource:
  url: jdbc:mysql://localhost:3306/your_database_name
  username: oytarijtest
  password: oytarijtest